### ISSUE TITLE
[DotNet][DateTime] Methods using hardcoded string instead of regex

### ISSUE THREAD

**Issue by Bill7zz** [southworks/Recognizers-Text#232]
**EnglishDatePeriodExtractorConfiguration** 
The class is using hardcoded strings variables instead of using a regex as in the other languages, both in Java and C#.

The method `GetFromTokenIndex` is using the method [EndsWith('From')](https://github.com/Microsoft/Recognizers-Text/blob/d892e384f23354039559e4bbe53758c78cee3dac/.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDatePeriodExtractorConfiguration.cs#L309) due to there is no regex for the case in which the 'From' word is at the end of the sentence. 

The method `GetBetweenTokenIndex` is using the method [EndsWith('Between')](https://github.com/Microsoft/Recognizers-Text/blob/d892e384f23354039559e4bbe53758c78cee3dac/.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDatePeriodExtractorConfiguration.cs#L321) due to there is no regex for the case in which the 'Between' word is at the end of the sentence.

Possible solution:
1. Add the patterns for the cases that end with the words 'From' and 'Between' which allow using the same logic implemented in another language.

2. Set 'From' and 'Between' as constants variables to avoid using hard-coded strings.

On the other hand, these two methods used by some extractors have the same logic but using different regexes during the evaluation. This can be improved by creating a module and make it external for it to be used by any of the extractors.

Eg:
Current state
![image](https://user-images.githubusercontent.com/37461749/51908621-16c58780-23a9-11e9-9610-f1ae097a93cc.png)

Proposed solution.
![image](https://user-images.githubusercontent.com/37461749/51908631-204eef80-23a9-11e9-8350-e6841976bbe7.png)

**EnglishHolidayParserConfiguration**
The method [GetSwiftYear ](https://github.com/Microsoft/Recognizers-Text/blob/d892e384f23354039559e4bbe53758c78cee3dac/.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishHolidayParserConfiguration.cs#L18)is using the methods `StartsWith("next")` , `StartsWith("last")` and `StartsWith("this")` instead using the pattern defined for this cases. 

_Possible solution_
1. Use the pattern defined for each case. 
eg: 
Use this: `EnglishDatePeriodParserConfiguration.NextPrefixRegex.IsMatch(trimmedText)`
instead `(trimmedText.StartsWith("next"))`

**Comment by VictorGrycuk** [comment]
@Bill7zz I suggest to add links to the lines where the hard coded strings are used:
> The method `GetFromTokenIndex` is using the method [EndsWith('From')](https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDatePeriodExtractorConfiguration.cs#L309) due to there is no regex for the case in which the 'From' word is at the end of the sentence.

That way whoever is reviewing the issue has a quick access to the lines in question.

**Comment by gasper-az** [comment]
@Bill7zz There are a few typos:

* Replace the `Fron` with `From` in the next case:

```
Set 'Fron' and 'Between' as constants...
```
* Also, add some missing `.` at the end of the lines.

* Replace the `eg. Use this` for `eg:` in the next text because it sounds repetitive:

```
eg.
Use this: EnglishDatePeriodParserConfiguration.NextPrefixRegex.IsMatch(trimmedText)
instead (trimmedText.StartsWith("next"))
```

* Finally, I'll suggest highlighting the `Possible Solution` subtitle, maybe with `bold` & `italic` format.

**Comment by Aliandi** [comment]
> Use the pattern defined for each case.
eg:
Use this: EnglishDatePeriodParserConfiguration.NextPrefixRegex.IsMatch(trimmedText)
instead (trimmedText.StartsWith("next"))

I am working with this parser on Java right now, and it will be refactored there. Check EnglishDateTime , there you should find all the strings that are hardcoded

**Comment by Bill7zz** [comment]
@JuanAr

**Comment by JuanAr** [comment]
I'd add a small one-line summary before the rest of the content. Mainly to state the same refactor is suitable for two rleated classes.

**Comment by denscollo** [comment]
Ok, will do it now 👍

**Comment by denscollo** [comment]
Replaced by #1462
