### ISSUE TITLE
MANX-233 [Java][DateTime]Extract code to avoid repetitions

### ISSUE THREAD

**Issue by Aliandi** [southworks/Recognizers-Text#238]
**Is your feature request related to a problem? Please describe.**
We noticed that the code in [SpanishDatePeriodParser ](https://github.com/Microsoft/Recognizers-Text/blob/c11cde1050952486dcf60c381616721e92c3aae2/Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/parsers/SpanishDatePeriodParserConfiguration.java#L530)is repeated in [EnglishDatePeriodParser](https://github.com/Microsoft/Recognizers-Text/blob/c11cde1050952486dcf60c381616721e92c3aae2/Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/parsers/EnglishDatePeriodParserConfiguration.java#L506), the common logic should be extracted to a different place.

**Describe the solution you'd like**
The code could be refactored to:

1. Change [IDatePeriodParserConfiguration ](https://github.com/microsoft/Recognizers-Text/blob/master/Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/config/IDatePeriodParserConfiguration.java)to an abstract class (rename also) and add the implementation of the repeated logic there. This class should extend from BaseOptionsConfiguration.

1. Make the parsers extend from the abstract class and refine the implementation of each one.

This way we would have a common abstract class to extend all language parsers to.

**Additional context**
Find bellow some images of the repeated logic:
![untitled](https://user-images.githubusercontent.com/22912283/51939223-b4db4100-23ed-11e9-89a6-13fd5c39aa34.png)

**Comment by VictorGrycuk** [comment]
@Aliandi Could you please add a link to the IDatePeriodParserConfiguration file and line? That way anyone reviewing the issue has a quick access the file in question.
Use a link to the MS repo.

Fix the typo `repeted` => `repeated`.

**Comment by Aliandi** [comment]
@VictorGrycuk something like how it is now?

**Comment by VictorGrycuk** [comment]
> @VictorGrycuk something like how it is now?

Perfect 👍
However, you are missing a space in `repeatedlogic`.

**Comment by VictorGrycuk** [comment]
Also, not sure if you are aware, but you are linking to files of a specific commit. If the file change, it wont be reflected on your links.

**Comment by Aliandi** [comment]
> 
> 
> Also, not sure if you are aware, but you are linking to files of a specific commit. If the file change, it wont be reflected on your links.

Thats the only way I found to direct to an specific line in the code
