### ISSUE TITLE
[StyleCop] Enable StyleCop in DataDrivenTests once ported to NetCore

### ISSUE THREAD

**Issue by Aliandi** [southworks/Recognizers-Text#247]
**Issue**
To enforce StyleCop compliance, the build process was configured to fail when an SA warning is found in #1425.
However, to avoid #1425 being blocked by #1050 while the DataDrivenTests project was being modified and since there was a merge conflict, we decided to temporarily exclude this project from breaking build due to SA warnings by removing the StyleCop NuGet package.

**Action to take**
Once the DataDrivenTests Project is done with the porting (#1050), the package should be added again so that this project is also part of the StyleCop analysis

**Comment by VictorGrycuk** [comment]
LGTM!

**Comment by JuanAr** [comment]
Edited issue description, exactly same message, just reordered, simplified, consolidated, refactored ~code~ words.

**Comment by denscollo** [comment]
Replaced by #1447
